# 2018年からflex環境でも3系が動くようになった
# 2系の場合と設定がやや異なるため原著をやや修正
# 変更点の詳細は[こちら](https://cloud.google.com/appengine/docs/standard/python3/python-differences)
runtime: python
runtime_config:
  python_version: 3

env: flex
service: default
manual_scaling:
  instances: 1
# timeoutを長めに設定しないのworkerがtimeout担って落ちる
entrypoint: gunicorn -b :$PORT ingestapp:app --timeout 120


env_variables:
  # 自身の設定したbucket名に適宜書き換え
  CLOUD_STORAGE_BUCKET: flight-records-sds-hase

